/**
 * Types for instruction management system
 */

export interface InstructionLayer {
  name: string;
  path: string;
  priority: number; // Higher priority overrides lower
}

export interface InstructionSection {
  marker: string;
  content: string;
  source: 'core' | 'meta' | 'project';
}

export interface AssemblyResult {
  content: string;
  sections: InstructionSection[];
  timestamp: Date;
  sources: string[];
}

export interface AssemblyOptions {
  preserveProjectSpecific?: boolean;
  includeMetadata?: boolean;
  targetPath?: string;
  isMetaSupervisor?: boolean; // True for meta-supervisor, includes README/QUICK-START
}

export interface InstructionMetadata {
  version: string;
  lastUpdated: Date;
  layers: string[];
  autoGenerated: boolean;
}
